apiVersion: batch/v1
kind: Job
metadata: {name: manual-failover, namespace: $KUBE_NAMESPACE}
spec:
  template:
    metadata: {name: manual-failover}
    spec:
      containers:
      - command: [/mssql-server-k8s-failover]
        env:
        - {name: MSSQL_K8S_AG_NAME, value: $KUBE_NAMESPACE}
        - {name: MSSQL_K8S_NEW_PRIMARY, value: $PRIMARY_CONTAINER}
        - name: MSSQL_K8S_NAMESPACE
          valueFrom:
            fieldRef: {fieldPath: metadata.namespace}
        image: mcr.microsoft.com/mssql/ha:2019-latest
        name: manual-failover
      restartPolicy: Never
      serviceAccount: manual-failover