apiVersion: mssql.microsoft.com/v1
kind: SqlServer
metadata:
  labels: {name: mssql1-$SERVICE_SUFFIX, type: sqlservr}
  name: mssql1-$SERVICE_SUFFIX
  namespace: $KUBE_NAMESPACE
spec:
  acceptEula: true
  agentsContainerImage: mcr.microsoft.com/mssql/ha:2019-latest
  availabilityGroups: [$AVAILABILITY_GROUP_NAME]
  instanceRootVolumeClaimTemplate:
    accessModes: [ReadWriteOnce]
    resources:
      requests: {storage: 5Gi}
    storageClass: default
  masterKeyPassword:
    secretKeyRef: {key: masterkeypassword, name: sql-secrets}
  saPassword:
    secretKeyRef: {key: sapassword, name: sql-secrets}
  sqlServerPod:
    securityContext:
      runAsUser: 10001
      fsGroup: 10001
    volumes:
    - name: mssqldb
      persistentVolumeClaim:
        claimName: mssql1-data-pvc-$SERVICE_SUFFIX
    - name: mssqldbbackup
      persistentVolumeClaim:
        claimName: mssql-backup-pvc-$SERVICE_SUFFIX
  sqlServerContainer: 
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    volumeMounts:
    - name: mssqldb
      mountPath: /var/opt/mssql
    - name: mssqldbbackup
      mountPath: /backup
---
apiVersion: v1
kind: Service
metadata: {name: mssql1-$SERVICE_SUFFIX, namespace: $KUBE_NAMESPACE}
spec:
  ports:
  - {name: tds, port: 1433}
  selector: {name: mssql1-$SERVICE_SUFFIX, type: sqlservr}
  type: ClusterIP
---
apiVersion: mssql.microsoft.com/v1
kind: SqlServer
metadata:
  labels: {name: mssql2-$SERVICE_SUFFIX, type: sqlservr}
  name: mssql2-$SERVICE_SUFFIX
  namespace: $KUBE_NAMESPACE
spec:
  acceptEula: true
  agentsContainerImage: mcr.microsoft.com/mssql/ha:2019-latest
  availabilityGroups: [$AVAILABILITY_GROUP_NAME]
  instanceRootVolumeClaimTemplate:
    accessModes: [ReadWriteOnce]
    resources:
      requests: {storage: 5Gi}
    storageClass: default
  masterKeyPassword:
    secretKeyRef: {key: masterkeypassword, name: sql-secrets}
  saPassword:
    secretKeyRef: {key: sapassword, name: sql-secrets}
  sqlServerPod:
    securityContext:
      runAsUser: 10001
      fsGroup: 10001
    volumes:
    - name: mssqldb
      persistentVolumeClaim:
        claimName: mssql2-data-pvc-$SERVICE_SUFFIX
    - name: mssqldbbackup
      persistentVolumeClaim:
        claimName: mssql-backup-pvc-$SERVICE_SUFFIX
  sqlServerContainer: 
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    volumeMounts:
    - name: mssqldb
      mountPath: /var/opt/mssql
    - name: mssqldbbackup
      mountPath: /backup
---
apiVersion: v1
kind: Service
metadata: {name: mssql2-$SERVICE_SUFFIX, namespace: $KUBE_NAMESPACE}
spec:
  ports:
  - {name: tds, port: 1433}
  selector: {name: mssql2-$SERVICE_SUFFIX, type: sqlservr}
  type: ClusterIP
---
apiVersion: mssql.microsoft.com/v1
kind: SqlServer
metadata:
  labels: {name: mssql3-$SERVICE_SUFFIX, type: sqlservr}
  name: mssql3-$SERVICE_SUFFIX
  namespace: $KUBE_NAMESPACE
spec:
  acceptEula: true
  agentsContainerImage: mcr.microsoft.com/mssql/ha:2019-latest
  availabilityGroups: [$AVAILABILITY_GROUP_NAME]
  instanceRootVolumeClaimTemplate:
    accessModes: [ReadWriteOnce]
    resources:
      requests: {storage: 5Gi}
    storageClass: default
  masterKeyPassword:
    secretKeyRef: {key: masterkeypassword, name: sql-secrets}
  saPassword:
    secretKeyRef: {key: sapassword, name: sql-secrets}
  sqlServerPod:
    securityContext:
      runAsUser: 10001
      fsGroup: 10001
    volumes:
    - name: mssqldb
      persistentVolumeClaim:
        claimName: mssql3-data-pvc-$SERVICE_SUFFIX
    - name: mssqldbbackup
      persistentVolumeClaim:
        claimName: mssql-backup-pvc-$SERVICE_SUFFIX
  sqlServerContainer: 
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    volumeMounts:
    - name: mssqldb
      mountPath: /var/opt/mssql
    - name: mssqldbbackup
      mountPath: /backup
---
apiVersion: v1
kind: Service
metadata: {name: mssql3-$SERVICE_SUFFIX, namespace: $KUBE_NAMESPACE}
spec:
  ports:
  - {name: tds, port: 1433}
  selector: {name: mssql3-$SERVICE_SUFFIX, type: sqlservr}
  type: ClusterIP